### ISSUE TITLE
项目已被aiwb收录

### ISSUE THREAD

**Issue by dubi906w** [typed-sigterm/ex-caller#41]
https://github.com/Awesome-Iwb/Awesome-Iwb

aiwb是专门整理电子白板实用软件的列表，你的项目已经被添加到 https://github.com/Awesome-Iwb/Awesome-Iwb 中，如果需要修改的地方，可以在aiwb仓库中创建issue。

**Comment by typed-sigterm** [comment]
Awesome-Iwb/Awesome-Iwb#5

**Comment by typed-sigterm** [comment]
如果觉得还能入眼的话，麻烦点点 star 呗（
